---
#GENEREL DATA


#Don't edit the config version!
config_version: 3.0

# The time how long the players have to wait befor claiming their rewards again
# Please use minutes
# 1440 minutes is one day
wait_time: 1440

# These are the commands wich will be executed if the players get their rewards
# The commands will be executed trought the console
# {player} is the player who claimed his reward, {asplayer} to run the command as the sender
# IMPORTANT: Use \" instead of normal quotess
commands:
 - msg {player} You got your reward!
 - "give {player} diamond 1  {display:{Name:\"§r§l§4Reward\"}}"


# COMMAND
# For help with the command configuration ask me on discord. xD
command: "reward"
description: "Claim your reward"
usage: "reward"
aliases: ["claimreward"]


#MESSAGES


# This is the message wich appears when you don't have the permission to use /reward
no_permission: "§cYou don't have the permission to use /reward"

# This is the message wich appears when you try to do "/reward" trough the console
run_ingame: "§cPlease run this command in-game"

# This is the message wich appears when you have to wait until you can claim you're reward again
already_got_reward: "§cYou already got your reward today! You have to wait §e{hours} hours, {minutes} minutes, and {seconds} seconds§c!"

# This is the message wich appears when you got you're reward
got_reward_succes: "§aYou succesfully got your reward!"
...
